service: medivault-backend

useDotenv: true

custom:
  serverless-offline:
    noPrependStageInUrl: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  # Default stage (default: dev)
  stage: prod
  # Default region (default: us-east-1)
  region: ap-south-1
  environment:
    PORT: ${env:PORT}
    MONGO_CONNECTION_STRING: ${env:MONGO_CONNECTION_STRING}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
